image: vegansk/ubuntu-java-nodejs

variables:
  COURSIER_CACHE: cache/.coursier-cache

cache:
  paths:
    - cache/

test:
  script:
    - bin/sbt scalafmt::test test -sbt-launch-dir cache/.sbt/launchers -sbt-boot cache/.sbt/boot -ivy /root/.ivy2
