image: vegansk/ubuntu-java-nodejs

variables:
  COURSIER_CACHE: cache/.coursier-cache
  SBT_OPTS: -Dsbt.override.build.repos=true

cache:
  paths:
    - cache/

test:
  script:
    - bin/sbt scalafmt::test test -sbt-launch-dir cache/.sbt/launchers -sbt-boot cache/.sbt/boot -ivy cache/.ivy2
