scalaVersion in ThisBuild := "2.12.4"

lazy val generateSources = taskKey[Unit]("generateSources")

lazy val root = project.in(file("."))
  .enablePlugins(SculptorScalagenPlugin)
  .settings(
    version := "0.0.1",

    scalagenConfig := ScalagenConfig(
      imports = List(
        ScalagenImport("java.time.Instant"),
      ),
      types = List(
        ScalagenType("xs:date", "Instant"),
        ScalagenType("xs:dateTime", "Instant")
      ),
      header = Option("/* This file is autogenerated. DO NOT EDIT! */")
    ),

    scalagenTargetDirectory := file("src/main/scala"),

    scalagenXsdFiles := Seq(
      file("xsd") / "fes-2.0.xsd"
    ),

    generateSources := {
      scalagenGenerate.value
    },

    compile.in(Compile) := compile.in(Compile).dependsOn(generateSources).value

  )
