scalaVersion in ThisBuild := "2.12.4"

lazy val generateSources = taskKey[Unit]("generateSources")

val cats = "org.typelevel" %% "cats-core" % "1.0.0-RC1"
val circe = "io.circe" %% "circe-core" % "0.9.0-M2"

lazy val root = project.in(file("."))
  .enablePlugins(SculptorScalagenPlugin)
  .settings(
    version := "0.0.1",

    libraryDependencies ++= Seq(
      cats, circe
    ),

    scalagenConfig := ScalagenConfig(
      packageName = Option("com.github.vegansk"),
      imports = List(
        ScalagenImport("java.time.Instant"),
        ScalagenImport("cats._"),
        ScalagenImport("cats.instances._"),
        ScalagenImport("io.circe._"),
        ScalagenImport("io.circe.syntax._")
      ),
      types = List(
        ScalagenType("xs:date", "String"),
        ScalagenType("xs:dateTime", "String")
      ),
      header = Option("/* This file is autogenerated. DO NOT EDIT! */"),
      parameters = ScalagenParameters(
        generateComments = true,
        generateCatsEq = true,
        generateCirceCodecs = true
      )
    ),

    scalagenTargetDirectory := file("src/main/scala"),

    scalagenXsdFiles := Seq(
      file("xsd") / "fes-2.0.xsd"
    ),

    generateSources := {
      scalagenGenerate.value
    },

    compile.in(Compile) := compile.in(Compile).dependsOn(generateSources).value

  )
